== Sample source code for handling some sale entries
This is a sandbox repository solving a problem oh handling some sale entries in a creative way.
Uses JUnit 5 for testing.

== Building and Deploying
This is a Gradle multi-module project. Build it from scratch using:
----
gradle clean build
----

== Description of the Solution
The MessageGenerator generates Message instances.
Each Message contains:

* a MessageType instance
* a list of Sale objects
* an AdjustementType instance (relevant only if message type is ADJUSTEMENT)
* an Adjustement value (relevant only if message type is ADJUSTEMENT)

All of the above are randomly generated by the MessageGenerator wen creating a message.

The MessageProcessor processes messages generated by the MessageGenerator, depending on the message type.
Each message contains one or multiple Sale entries that will be stores using a SalesDao instance.

The SalesDao is a data access object class that handles Sale objects. the database is represented by the "container"
map.

A Sale instance has a product type field and a value. It also contains a method named "adjust" which is called to
adjust its value according to an adjustement type and value.

All object types are reresented by the specific enums: ProductType, MessageType, AdjustementType.

The main class is com.jp.Application.